### ISSUE TITLE
Move test into own directory

### ISSUE THREAD

**Issue by scripter-co** [sinonjs/samsam#28]
It'd be much easier from a config/publishing point of view to move `lib/samsa.test.js` into it's own folder under `./test`.

We'd be able to remove the following:
- https://github.com/sinonjs/samsam/blob/master/package.json#L29
- https://github.com/sinonjs/samsam/blob/master/.npmignore#L3

It'd also more closely follow other packages conventions. If not, we need to tidy up the following:

- https://github.com/sinonjs/samsam/blob/master/.eslintignore#L3
https://github.com/sinonjs/samsam/blob/master/.npmignore#L5

**Comment by mroderick** [comment]
`samsam` is following a convention of keeping unit test files next to the source files they're testing. This convention is used in all the projects that we've taken over maintenance of from `@busterjs`.

This has a few benefits:

* it's easy to move files around, you won't need to recalculate urls
* it's easy to open test files in visual editors, as they're right next to the source files
* it's easy to see where test files are missing

Because `samsam` is such a small library, these benefits do not make much of a difference in practice.

It does come with minor overhead when configuring publishing, which luckily is a very rare occurrence.

However, as we adopt the same practices and tools in all the `@sinonjs` projects, everything will be familiar and it'll be easy to switch from working on one to the other.
