### ISSUE TITLE
Version of lodash used is out of date

### ISSUE THREAD

**Issue by yshewchuk** [sinonjs/samsam#60]
The lodash library has a known vulnerability in versions <= 4.17.5 (https://nvd.nist.gov/vuln/detail/CVE-2018-3721) . Currently samsam is using lodash.get v4.4.2, which I don't believe is technically vulnerable, but is out of date. Since individual lodash functions are also no longer being published I think the best course of action is to switch to the full lodash library and update the version. Pull request to follow.

**Comment by mgred** [comment]
@yshewchuk as you said it yourself and as it is stated in the report you linked, the `get` method is not affected by this vulnerability, so I don't see a need to update this.

>  Since individual lodash functions are also no longer being published I think the best course of action is to switch to the full lodash library and update the version.

Why do you think that these packages are not published anymore? `lodash` still promotes to use them on their official documentation.

**Comment by yshewchuk** [comment]
Hi @mgred 

Part of the reason that I am requesting this is that some security scanning tools (in my case BlackDuck) associate individual function packages to the main package, which is listed as vulnerable. The tool then believes that the individual function is vulnerable and that makes it difficult to address the issue and requires a manual intervention in the tool (for the main lodash I can force it to use the latest, but for the individual functions there is no way to update since you're already using the latest version of that function). 

I believe that the individual packages are no longer published because I saw a few recent issues where people are requesting updated function packages and the issue does not seem to be addressed (see https://github.com/lodash/lodash/issues/2727 and https://github.com/lodash/lodash/issues/4042). It is documented on their roadmap for this year to officially drop support for them (https://github.com/lodash/lodash/wiki/Roadmap).

Thanks for your consideration

**Comment by mgred** [comment]
Hey @yshewchuk, thanks for your detailed explanation on the situation.

> Part of the reason that I am requesting this is that some security scanning tools (in my case BlackDuck) associate individual function packages to the main package, which is listed as vulnerable. The tool then believes that the individual function is vulnerable and that makes it difficult to address the issue and requires a manual intervention in the tool (for the main lodash I can force it to use the latest, but for the individual functions there is no way to update since you're already using the latest version of that function).

I can understand this hassle even though I have no clue about the tool itself. However, I think it's not the task of a library like `samsam` to _fix_ any security scanning setups in dependent software. And in that case it seems to be marked as _vulnarable_ because of its (old) version rather than its functionality.


> I believe that the individual packages are no longer published because I saw a few recent issues where people are requesting updated function packages and the issue does not seem to be addressed (see [lodash/lodash#2727](https://github.com/lodash/lodash/issues/2727) and [lodash/lodash#4042](https://github.com/lodash/lodash/issues/4042)). It is documented on their roadmap for this year to officially drop support for them (https://github.com/lodash/lodash/wiki/Roadmap).

Okay, it makes sense to - sooner or later - get something more up-to-date or align with `lodash`'s releases if we want continue using this functionality, but for now this packages is not officially deprecated. So I personally don't see any need in updating right now.

What do other maintainers say? @mantoni @mroderick any opinion?

Thanks

**Comment by mantoni** [comment]
@mgred I agree with your point of view. In addition, we already have security scans on GitHub and npm where the results can be confirmed by the team. I'm absolutely pro for reacting to security incidents, but we need a way to verify the issue and also verify that a particular patch removes the problem. I don't see this here.

Slightly off topic, and partly due to the discussion here, I think it makes sense to keep dependencies to a minimum. In case of `_.get`, I can only see it being used in `match.hasNested` so that this is possible:

```js
var hasNested = createMatcher.hasNested("foo[0].bar", "doo");

assert(hasNested.test({ foo: [{ bar: "doo" }] }));
```

I'm not sure we actually want to keep supporting this. If we drop this feature, we can remove the lodash dependency entirely.

**Comment by mgred** [comment]
@mantoni 

> Slightly off topic, and partly due to the discussion here, I think it makes sense to keep dependencies to a minimum. 

Agree 👍 

> I'm not sure we actually want to keep supporting this. If we drop this feature, we can remove the lodash dependency entirely.

Getting rid of unnecessary code and dependencies is always good. The lesser the better 🥇 

In the particular case of `hasNested`, I'm not sure if we can simply remove this functionality, since I don't know about its importance/usage.

If we want to get rid of it, because its not a commonly used feature we could maybe export it into some kind of _Extra_ package, so we can narrow a _Core_ which has the most important and also ideally dependecieless features.

**Comment by mantoni** [comment]
It's clearly a breaking change to remove it. We have a repository with [examples for custom referee assertion](https://github.com/sinonjs/referee-custom-assertions). We could create a new one with examples for custom matchers. The `hasNested` matcher could be moved there which gives people who depend on the feature a nice upgrade path.

Anyhow, while we're talking this through, GitHub now also warns about a potential security issue with the lodash version used 😆 I'm going to fix the issue with a patch now.

**Comment by mantoni** [comment]
Sorry @yshewchuk for being a bit passive about this one initially. Like I said, we need a way to verify the issue and apparently it took a little while until the issue was highlighted by GitHub and npm as well. With samsam `v3.1.1` the GitHub warning is gone. 🙏

**Comment by mgred** [comment]
> We could create a new one with examples for custom matchers. The `hasNested` matcher could be moved there which gives people who depend on the feature a nice upgrade path.

Nice idea 👍
